"""Initial schema

Revision ID: 89073ac8a3d1
Revises: 30b2a3693d47
Create Date: 2025-06-27 18:30:23.869436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89073ac8a3d1'
down_revision: Union[str, Sequence[str], None] = '30b2a3693d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('is_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'is_completed')
    # ### end Alembic commands ###
